default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  hostname: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: arkatest
  
test:
  <<: *default
  database: arkatest

production:
  <<: *default
  database: arkatest
